site_name: Î–ÎµÏÎ¯Ï„Î±
docs_dir: "../../docs/el"
site_dir: "../../site/el"

repo_name: zerita-lang/zerita
repo_url: https://github.com/zerita-lang/zerita/

nav:
  - Î‘ÏÏ‡Î¹ÎºÎ®: index.md
  - Î•Ï€Î¹ÏƒÎºÏŒÏ€Î·ÏƒÎ· Ï„Î·Ï‚ Î¶ÎµÏÎ¯Ï„Î±:
      - overview/index.md
      - Î›ÎµÎ¾Î¹ÎºÏŒ: https://zerita-lang.github.io/dictionary/el/
      - Î£Ï…Î½Ï„Î±ÎºÏ„Î¹ÎºÏŒ:
          - overview/syntax/index.md
          # - Î¦ÏÎ¬ÏƒÎµÎ¹Ï‚: overview/syntax/phrases.md
          # - Î›Î­Î¾ÎµÎ¹Ï‚ ÎºÎ±Î¹ Î»ÎµÎ¾Î®Î¼Î±Ï„Î±: overview/syntax/words.md
      - ÎŸÏÎ¸Î¿Î³ÏÎ±Ï†Î¯Î±: overview/orthography.md
  # - Î ÏÎ¿ÏƒÎ´Î¹Î¿ÏÎ¹ÏƒÏ„Î¹ÎºÎ¬:
  #     - determinatives/index.md
  #     - Î†ÏÎ¸ÏÎ±: determinatives/articles.md
  #     - Î”ÎµÎ¹ÎºÏ„Î¹ÎºÎ¬: determinatives/demonstratives.md
  #     - ÎšÏ„Î·Ï„Î¹ÎºÎ¬: determinatives/possessives.md
  #     - Î Î¿ÏƒÎ¿Î´ÎµÎ¯ÎºÏ„ÎµÏ‚: determinatives/quantifiers.md
  #     - Î‘ÏÎ¹Î¸Î¼Î·Ï„Î¹ÎºÎ¬: determinatives/numerals.md
  # - ÎŸÏ…ÏƒÎ¹Î±ÏƒÏ„Î¹ÎºÎ¬:
  #     - nouns/index.md
  #     - Î“Î­Î½Î¿Ï‚: nouns/gender.md
  #     - ÎšÎ»Î¬ÏƒÎ·: nouns/class.md
  #     - Î‘ÏÎ¹Î¸Î¼ÏŒÏ‚: nouns/number.md
  #     - Î Ï„ÏÏƒÎµÎ¹Ï‚: nouns/cases.md
  #     - Î‘Î½Ï„Ï‰Î½Ï…Î¼Î¯ÎµÏ‚:
  #         - nouns/pronouns/index.md
  #         - Î ÏÎ¿ÏƒÏ‰Ï€Î¹ÎºÎ­Ï‚ Î±Î½Ï„Ï‰Î½Ï…Î¼Î¯ÎµÏ‚: nouns/pronouns/personal.md
  #     - Î Î¯Î½Î±ÎºÎµÏ‚ ÎºÎ»Î¯ÏƒÎ·Ï‚: nouns/declension.md
  # - Î¡Î®Î¼Î±Ï„Î±:
  #     - verbs/index.md
  #     - Î¤ÏÏ€Î¿Ï‚: verbs/type.md
  #     - Î ÏÏŒÏƒÏ‰Ï€Î¿ ÎºÎ±Î¹ Î±ÏÎ¹Î¸Î¼ÏŒÏ‚: verbs/person.md
  #     - Î§ÏÏŒÎ½Î¿Ï‚: verbs/tense.md
  #     - ÎˆÎ³ÎºÎ»Î¹ÏƒÎ·: verbs/mood.md
  #     - Î Î¯Î½Î±ÎºÎµÏ‚ ÎºÎ»Î¯ÏƒÎ·Ï‚: verbs/declension.md
  # - Î ÎµÏÎ¹Î³ÏÎ±Ï†Î®:
  #     - description/index.md
  #     - Î•Ï€Î¯Î¸ÎµÏ„Î±:
  #         - description/adjectives/index.md
  #         - Î’Î±Î¸Î¼ÏŒÏ‚: description/adjectives/grade.md
  #     - Î•Ï€Î¹ÏÏÎ®Î¼Î±Ï„Î±:
  #         - description/adverbs/index.md
  #         - Î Î±ÏÎ¬Î³Ï‰Î³Î± ÎµÏ€Î¹ÏÏÎ®Î¼Î±Ï„Î±: description/adverbs/derived.md
  # - Î£Ï…Î½Î´Î­ÏƒÎµÎ¹Ï‚:
  #     - connection/index.md
  #     - Î£Ï…Î½Ï„Î¿Î½Î¹ÏƒÎ¼ÏŒÏ‚: connection/coordination.md
  #     - Î¥Ï€Î¿Ï„Î±Î³Î®: connection/subordination.md
  #     - Î£Ï‡ÎµÏ„Î¹ÎºÎ­Ï‚ Ï€ÏÎ¿Ï„Î¬ÏƒÎµÎ¹Ï‚: connection/relative.md
  #     - Î ÏÎ¿Î¸Î­ÏƒÎµÎ¹Ï‚: connection/prepositions.md
  #     - ÎœÏŒÏÎ¹Î±: connection/particles.md
  # - Î¥Ï€Î¿Î¸ÎµÏ„Î¹ÎºÎ­Ï‚ Ï€ÏÎ¿Ï„Î¬ÏƒÎµÎ¹Ï‚:
  #     - conditionals/index.md
  #     - Î¥Ï€ÏŒÎ¸ÎµÏƒÎ·: conditionals/antecedent.md
  #     - Î‘Ï€ÏŒÎ´Î¿ÏƒÎ·: conditionals/consequent.md
  # - Î•ÏÏ‰Ï„Î®ÏƒÎµÎ¹Ï‚:
  #     - questions/index.md
  #     - Î•ÏÏ‰Ï„Î·Î¼Î±Ï„Î¹ÎºÎ¬: questions/interrogatives.md
  #     - Î•Ï€Î¹Ï†Ï‰Î½Î®Î¼Î±Ï„Î±: questions/interjection.md
  #     - Î†ÏÎ½Î·ÏƒÎ·: questions/negation.md

markdown_extensions:
  - pymdownx.highlight:
      use_pygments: true
  - admonition
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.snippets

theme:
  name: material
  language: el

  icon:
    repo: fontawesome/brands/github

  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Î‘Î»Î»Î±Î³Î® ÏƒÎµ ÏƒÎºÎ¿Ï„ÎµÎ¹Î½Î® Î»ÎµÎ¹Ï„Î¿Ï…ÏÎ³Î¯Î±

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Î‘Î»Î»Î±Î³Î® ÏƒÎµ Ï†Ï‰Ï„ÎµÎ¹Î½Î® Î»ÎµÎ¹Ï„Î¿Ï…ÏÎ³Î¯Î±

  features:
    - content.code.annotate
    - content.code.copy
    - navigation.indexes
    - navigation.instant
    - navigation.instant.progress
    - navigation.top
    - navigation.tracking
    - search
    - search.suggest
    - search.share

plugins:
  - search:
      lang: el

extra:
  alternate:
    - name: ğŸ‡¬ğŸ‡§ English
      link: /zerita/en/
      lang: en
    - name: ğŸ‡¬ğŸ‡· Î•Î»Î»Î·Î½Î¹ÎºÎ¬
      link: /zerita/el/
      lang: el
